version: '2'
services:
  ie:
    build: .
    ports:
      - "3001"
    depends_on:
      - mongodb
    environment:
      # The values below should not be modified under normal circumstances
      - HUDDLE_CONFIGS=./config/multifactor_huddle_config.json
      - MONGO_URL=mongodb://mongodb:27017
      - RISK_SERVICE_URL=http://multifactorriskservice:9000
      - GIN_MODE=release
    command: dockerize -wait tcp://mongodb:27017 -timeout 300s ./server -loadCodes
  endpoint:
    build: ../ie-ccda-endpoint
    ports:
      - "3000"
    depends_on:
      - ie
    environment:
      # The value below should not be modified under normal circumstances
      - FHIR_URL=http://ie:3001
  mongodb:
    image: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - "27017"
  multifactorriskservice:
    build: ../multifactorriskservice
    ports:
      - "9000"
    depends_on:
      - ie
      - mongodb
    environment:
      # REDCAP_URL and REDCAP_TOKEN must be set to valid values before running!
      - REDCAP_URL=http://myredcapserver/redcap/api
      - REDCAP_TOKEN=MYREDCAPTOKEN
      # The values below should not be modified under normal circumstances
      - FHIR_URL=http://ie:3001
      - MONGO_URL=mongodb://mongodb:27017
      - HTTP_HOST_AND_PORT=multifactorriskservice:9000
      - GIN_MODE=release
    command: dockerize -wait tcp://mongodb:27017 -timeout 300s ./multifactorriskservice
    # command: dockerize -wait tcp://mongodb:27017 -timeout 300s ./mock # for testing only!
  integrator:
    build: ../integrator
    depends_on:
      - ie
      - mongodb
      - endpoint
    volumes:
      - /data/integrator:/data/integrator
    environment:
      # The following variables all have site-specific values -- they must be set before running!
      - HIE_URL=http://myhieserver/api
      - HIE_USER=myhieusername
      - HIE_PASSWORD=myhiepassword
      # The following file should be created and edited before running
      # Each line of the file should contain an EE to ingest data for
      - EE_FILE=/data/integrator/ee_file.txt
      # The values below may need to be modified in some environments
      - USE_CURL=true
      - INTEGRATOR_CRON=0 0 20 * * *
      - INTEGRATOR_NOW=true
      # The values below should not be modified under normal circumstances
      - INGEST_URL=http://endpoint:3000/ccda
      - MONGO_URL=mongodb://mongodb:27017
      #- COPY_DIR=/data/integrator/ccda # for debugging only
    command: dockerize -wait http://endpoint:3000 -wait tcp://mongodb:27017 -timeout 300s ./integrator
  nginx:
    build: ../nginx
    ports:
      - "443:443"
    depends_on:
      - ie
      - multifactorriskservice
    environment:
      # The value below should not be modified under normal circumstances
      - IE_URL=http://ie:3001
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf '$$IE_URL' && nginx -g 'daemon off;'"
