ie:
  build: .
  ports:
    - "3001"
  links:
    - mongodb:mongo
  command: ./server -huddle ./configs/multifactor_huddle_config.json
endpoint:
  build: ../ie-ccda-endpoint
  ports:
    - "3000:3000"
  links:
    - ie
mongodb:
  image: mongo
  volumes:
    - /data/db:/data/db
  ports:
    - "27017"
multifactorriskservice:
  build: ../multifactorriskservice
  ports:
    - "9000"
  links:
    - mongodb:mongo
    - ie
  command: ./multifactorriskservice -redcap https://your_redcap_server/redcap/api -token your_redcap_api_token -fhir http://ie:3001
nginx:
  build: ../nginx
  ports:
    - "443:443"
  links:
    - ie
  command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf '$$IE_PORT_3001_TCP_ADDR:$$IE_PORT_3001_TCP_PORT' && nginx -g 'daemon off;'"
