ie:
  build: .
  ports:
    - "3001:3001"
  links:
    - mongodb:mongo
    - riskservice:riskservice
  command: /go/src/github.com/intervention-engine/ie/server -huddle /go/src/github.com/intervention-engine/ie/configs/multifactor_huddle_config.json
endpoint:
  build: ../ie-ccda-endpoint
  ports:
    - "3000:3000"
  links:
    - ie
mongodb:
  image: mongo
  volumes:
    - /data/db:/data/db
  ports:
    - "27017:27017"
riskservice:
  build: ../riskservice
  ports:
    - "9000:9000"
  links:
    - mongodb:mongo
nginx:
  build: ../nginx
  ports:
    - "8080:8080"
    - "443:443"
  links:
    - ie
  command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf '$$IE_PORT_3001_TCP_ADDR:$$IE_PORT_3001_TCP_PORT' && nginx -g 'daemon off;'"
