consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Careteam:
    description: A care team (default view)
    example:
      createdAt: 1976-09-25T22:49:04-04:00
      id: Voluptatem ullam.
      leader: Sit dolor neque nulla.
      name: Nisi dolorum.
    properties:
      createdAt:
        description: Timestamp for care team creation
        example: 1976-09-25T22:49:04-04:00
        format: date-time
        type: string
      id:
        description: Unique care team ID
        example: Voluptatem ullam.
        type: string
      leader:
        description: Care team leader
        example: Sit dolor neque nulla.
        type: string
      name:
        description: Care team name
        example: Nisi dolorum.
        type: string
    title: 'Mediatype identifier: application/vnd.careteam+json; view=default'
    type: object
  CareteamCollection:
    description: CareteamCollection is the media type for an array of Careteam (default
      view)
    example:
    - createdAt: 1976-09-25T22:49:04-04:00
      id: Voluptatem ullam.
      leader: Sit dolor neque nulla.
      name: Nisi dolorum.
    items:
      $ref: '#/definitions/Careteam'
    title: 'Mediatype identifier: application/vnd.careteam+json; type=collection;
      view=default'
    type: array
  CreateCareTeamPayload:
    example:
      createdAt: 1970-07-27T08:23:11-04:00
      id: At omnis aut consequatur id eos cumque.
      leader: Aut occaecati.
      name: Quis deleniti earum qui autem rerum temporibus.
    properties:
      createdAt:
        description: Timestamp for care team creation
        example: 1970-07-27T08:23:11-04:00
        format: date-time
        type: string
      id:
        description: Unique care team ID
        example: At omnis aut consequatur id eos cumque.
        type: string
      leader:
        description: Care team leader
        example: Aut occaecati.
        type: string
      name:
        description: Care team name
        example: Quis deleniti earum qui autem rerum temporibus.
        type: string
    required:
    - name
    - leader
    title: CreateCareTeamPayload
    type: object
  Patient:
    description: A patient (default view)
    example:
      address:
        city: Cum aut blanditiis accusantium molestiae et.
        postalCode: Tempora et.
        state: Sapiente incidunt quia quo alias aut.
        street:
        - Eveniet vel nesciunt omnis est ducimus est.
        - Eveniet vel nesciunt omnis est ducimus est.
        - Eveniet vel nesciunt omnis est ducimus est.
      age: 7.384679e+18
      birthDate: 2000-07-16T01:52:47-04:00
      gender: Non nostrum.
      id: Explicabo quas est minus.
      name:
        family: Aut mollitia illum quia.
        full: Suscipit quis exercitationem ut ipsum quis saepe.
        given: Cum repellat tempora eum.
        middleInitial: Qui et et.
      riskAssessments:
      - date: 2008-12-18T15:13:10-05:00
        groupId: Et et deserunt voluptates doloribus est nihil.
        id: Sit ut aut.
        value: 2.5970094e+18
    properties:
      address:
        $ref: '#/definitions/address'
      age:
        description: Age of Patient
        example: 7.384679e+18
        format: int64
        type: integer
      birthDate:
        description: Birth Date of Patient
        example: 2000-07-16T01:52:47-04:00
        format: date-time
        type: string
      gender:
        description: Gender of Patient
        example: Non nostrum.
        type: string
      id:
        description: Unique patient ID
        example: Explicabo quas est minus.
        type: string
      name:
        example:
          family: Aut mollitia illum quia.
          full: Suscipit quis exercitationem ut ipsum quis saepe.
          given: Cum repellat tempora eum.
          middleInitial: Qui et et.
        properties:
          family:
            description: Family Name
            example: Aut mollitia illum quia.
            type: string
          full:
            description: Full Name
            example: Suscipit quis exercitationem ut ipsum quis saepe.
            type: string
          given:
            description: Given Name
            example: Cum repellat tempora eum.
            type: string
          middleInitial:
            description: Middle Initial
            example: Qui et et.
            type: string
        type: object
      riskAssessments:
        example:
        - date: 2008-12-18T15:13:10-05:00
          groupId: Et et deserunt voluptates doloribus est nihil.
          id: Sit ut aut.
          value: 2.5970094e+18
        items:
          $ref: '#/definitions/riskAssessment'
        type: array
    required:
    - id
    - name
    title: 'Mediatype identifier: application/vnd.patient+json; view=default'
    type: object
  PatientCollection:
    description: PatientCollection is the media type for an array of Patient (default
      view)
    example:
    - address:
        city: Cum aut blanditiis accusantium molestiae et.
        postalCode: Tempora et.
        state: Sapiente incidunt quia quo alias aut.
        street:
        - Eveniet vel nesciunt omnis est ducimus est.
        - Eveniet vel nesciunt omnis est ducimus est.
        - Eveniet vel nesciunt omnis est ducimus est.
      age: 7.384679e+18
      birthDate: 2000-07-16T01:52:47-04:00
      gender: Non nostrum.
      id: Explicabo quas est minus.
      name:
        family: Aut mollitia illum quia.
        full: Suscipit quis exercitationem ut ipsum quis saepe.
        given: Cum repellat tempora eum.
        middleInitial: Qui et et.
      riskAssessments:
      - date: 2008-12-18T15:13:10-05:00
        groupId: Et et deserunt voluptates doloribus est nihil.
        id: Sit ut aut.
        value: 2.5970094e+18
    items:
      $ref: '#/definitions/Patient'
    title: 'Mediatype identifier: application/vnd.patient+json; type=collection; view=default'
    type: array
  UpdateCareTeamPayload:
    example:
      createdAt: 1970-07-27T08:23:11-04:00
      id: At omnis aut consequatur id eos cumque.
      leader: Aut occaecati.
      name: Quis deleniti earum qui autem rerum temporibus.
    properties:
      createdAt:
        description: Timestamp for care team creation
        example: 1970-07-27T08:23:11-04:00
        format: date-time
        type: string
      id:
        description: Unique care team ID
        example: At omnis aut consequatur id eos cumque.
        type: string
      leader:
        description: Care team leader
        example: Aut occaecati.
        type: string
      name:
        description: Care team name
        example: Quis deleniti earum qui autem rerum temporibus.
        type: string
    required:
    - id
    - name
    - leader
    - createdAt
    title: UpdateCareTeamPayload
    type: object
  address:
    example:
      city: Cum aut blanditiis accusantium molestiae et.
      postalCode: Tempora et.
      state: Sapiente incidunt quia quo alias aut.
      street:
      - Eveniet vel nesciunt omnis est ducimus est.
      - Eveniet vel nesciunt omnis est ducimus est.
      - Eveniet vel nesciunt omnis est ducimus est.
    properties:
      city:
        description: City Name
        example: Cum aut blanditiis accusantium molestiae et.
        type: string
      postalCode:
        description: Postal Code
        example: Tempora et.
        type: string
      state:
        description: State Name
        example: Sapiente incidunt quia quo alias aut.
        type: string
      street:
        description: Street Name
        example:
        - Eveniet vel nesciunt omnis est ducimus est.
        - Eveniet vel nesciunt omnis est ducimus est.
        - Eveniet vel nesciunt omnis est ducimus est.
        items:
          example: Eveniet vel nesciunt omnis est ducimus est.
          type: string
        type: array
    title: address
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
  riskAssessment:
    example:
      date: 2008-12-18T15:13:10-05:00
      groupId: Et et deserunt voluptates doloribus est nihil.
      id: Sit ut aut.
      value: 2.5970094e+18
    properties:
      date:
        description: Date
        example: 2008-12-18T15:13:10-05:00
        format: date-time
        type: string
      groupId:
        description: Risk Assessment Group ID
        example: Et et deserunt voluptates doloribus est nihil.
        type: string
      id:
        description: Risk Assessment ID
        example: Sit ut aut.
        type: string
      value:
        description: Value
        example: 2.5970094e+18
        format: int64
        type: integer
    title: riskAssessment
    type: object
host: localhost:3001
info:
  description: An api used to interact with Intervention Engine
  license:
    name: Apache 2.0
    url: https://github.com/intervention-engine/ie/blob/master/LICENSE
  title: The Intervention Engine Web API
  version: ""
paths:
  /api/care_teams:
    get:
      description: List all care teams.
      operationId: care_team#list
      produces:
      - application/vnd.careteam+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/CareteamCollection'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      schemes:
      - http
      summary: list care_team
      tags:
      - care_team
    post:
      description: Create care team.
      operationId: care_team#create
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/CreateCareTeamPayload'
      produces:
      - application/vnd.careteam+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Careteam'
        "201":
          description: Created
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      schemes:
      - http
      summary: create care_team
      tags:
      - care_team
  /api/care_teams/{id}:
    delete:
      description: Delete care team.
      operationId: care_team#delete
      parameters:
      - in: path
        name: id
        required: true
        type: string
      produces:
      - application/vnd.careteam+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Careteam'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      schemes:
      - http
      summary: delete care_team
      tags:
      - care_team
    get:
      description: Get care team by id.
      operationId: care_team#show
      parameters:
      - description: Care team ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/vnd.careteam+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Careteam'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      schemes:
      - http
      summary: show care_team
      tags:
      - care_team
    put:
      description: Update care team.
      operationId: care_team#update
      parameters:
      - in: path
        name: id
        required: true
        type: string
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UpdateCareTeamPayload'
      produces:
      - application/vnd.careteam+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Careteam'
        "204":
          description: No Content
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      schemes:
      - http
      summary: update care_team
      tags:
      - care_team
  /api/patients:
    get:
      description: List all patients.
      operationId: patient#list
      parameters:
      - in: query
        minimum: 1
        name: page
        required: false
        type: integer
      - in: query
        minimum: 1
        name: per_page
        required: false
        type: integer
      - in: query
        name: sort_by
        required: false
        type: string
      produces:
      - application/vnd.patient+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PatientCollection'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      schemes:
      - http
      summary: list patient
      tags:
      - patient
  /api/patients/{id}:
    get:
      description: Get patient by id.
      operationId: patient#show
      parameters:
      - description: Patient ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/vnd.patient+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Patient'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      schemes:
      - http
      summary: show patient
      tags:
      - patient
  /swagger-ui/{filepath}:
    get:
      operationId: swagger#/swagger-ui/*filepath
      parameters:
      - description: Relative file path
        in: path
        name: filepath
        required: true
        type: string
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: Download swagger-ui/
  /swagger.json:
    get:
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      summary: Download swagger/swagger.json
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  Created:
    description: Created
  NoContent:
    description: No Content
  RCreated:
    description: Resource created
    headers:
      Link:
        type: string
  RNotFound:
    description: Resource not found
schemes:
- http
swagger: "2.0"
